services:
  mysql:
    container_name: gdos_ms_mysql
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: GDOS
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - 3307:3306
    networks:
      - microservices-net
    restart: unless-stopped

  phpmyadmin:
    container_name: gdos_ms_phpmyadmin
    image: phpmyadmin:latest
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    restart: unless-stopped
    ports:
      - 8080:80
    networks:
      - microservices-net

  mail-dev:
    container_name: ms_mail_dev
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025
    networks:
      - microservices-net

networks:
  microservices-net:
    driver: bridge

volumes:
  db-data: